export const elderAerobicPowerConfig = [
  {
    gender: "Male",
    age: 60,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Male", age: 60, threshold: 578, classification: "Ideal" },
  {
    gender: "Male",
    age: 60,
    threshold: 673,
    classification: "Acima do esperado",
  },
  {
    gender: "Male",
    age: 65,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Male", age: 65, threshold: 512, classification: "Ideal" },
  {
    gender: "Male",
    age: 65,
    threshold: 641,
    classification: "Acima do esperado",
  },
  {
    gender: "Male",
    age: 70,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Male", age: 70, threshold: 498, classification: "Ideal" },
  {
    gender: "Male",
    age: 70,
    threshold: 623,
    classification: "Acima do esperado",
  },
  {
    gender: "Male",
    age: 75,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Male", age: 75, threshold: 430, classification: "Ideal" },
  {
    gender: "Male",
    age: 75,
    threshold: 586,
    classification: "Acima do esperado",
  },
  {
    gender: "Male",
    age: 80,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Male", age: 80, threshold: 407, classification: "Ideal" },
  {
    gender: "Male",
    age: 80,
    threshold: 554,
    classification: "Acima do esperado",
  },
  {
    gender: "Male",
    age: 85,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Male", age: 85, threshold: 348, classification: "Ideal" },
  {
    gender: "Male",
    age: 85,
    threshold: 522,
    classification: "Acima do esperado",
  },
  {
    gender: "Male",
    age: 90,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Male", age: 90, threshold: 279, classification: "Ideal" },
  {
    gender: "Male",
    age: 90,
    threshold: 458,
    classification: "Acima do esperado",
  },
  {
    gender: "Female",
    age: 60,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Female", age: 60, threshold: 498, classification: "Ideal" },
  {
    gender: "Female",
    age: 60,
    threshold: 605,
    classification: "Acima do esperado",
  },
  {
    gender: "Female",
    age: 65,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Female", age: 65, threshold: 457, classification: "Ideal" },
  {
    gender: "Female",
    age: 65,
    threshold: 582,
    classification: "Acima do esperado",
  },
  {
    gender: "Female",
    age: 70,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Female", age: 70, threshold: 439, classification: "Ideal" },
  {
    gender: "Female",
    age: 70,
    threshold: 563,
    classification: "Acima do esperado",
  },
  {
    gender: "Female",
    age: 75,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Female", age: 75, threshold: 393, classification: "Ideal" },
  {
    gender: "Female",
    age: 75,
    threshold: 536,
    classification: "Acima do esperado",
  },
  {
    gender: "Female",
    age: 80,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Female", age: 80, threshold: 352, classification: "Ideal" },
  {
    gender: "Female",
    age: 80,
    threshold: 495,
    classification: "Acima do esperado",
  },
  {
    gender: "Female",
    age: 85,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Female", age: 85, threshold: 311, classification: "Ideal" },
  {
    gender: "Female",
    age: 85,
    threshold: 467,
    classification: "Acima do esperado",
  },
  {
    gender: "Female",
    age: 90,
    threshold: 0,
    classification: "Abaixo do esperado",
  },
  { gender: "Female", age: 90, threshold: 251, classification: "Ideal" },
  {
    gender: "Female",
    age: 90,
    threshold: 403,
    classification: "Acima do esperado",
  },
];
