export const exerciseConfig = [
  { gender: "Male", exercise: "bench_press", threshold: 1.5, points: 10 },
  { gender: "Male", exercise: "bench_press", threshold: 1.4, points: 9 },
  { gender: "Male", exercise: "bench_press", threshold: 1.3, points: 8 },
  { gender: "Male", exercise: "bench_press", threshold: 1.2, points: 7 },
  { gender: "Male", exercise: "bench_press", threshold: 1.1, points: 6 },
  { gender: "Male", exercise: "bench_press", threshold: 1.0, points: 5 },
  { gender: "Male", exercise: "bench_press", threshold: 0.9, points: 4 },
  { gender: "Male", exercise: "bench_press", threshold: 0.8, points: 3 },
  { gender: "Male", exercise: "bench_press", threshold: 0.7, points: 2 },
  { gender: "Male", exercise: "bench_press", threshold: 0.6, points: 1 },
  { gender: "Male", exercise: "barbell_curl", threshold: 0.7, points: 10 },
  { gender: "Male", exercise: "barbell_curl", threshold: 0.65, points: 9 },
  { gender: "Male", exercise: "barbell_curl", threshold: 0.6, points: 8 },
  { gender: "Male", exercise: "barbell_curl", threshold: 0.55, points: 7 },
  { gender: "Male", exercise: "barbell_curl", threshold: 0.5, points: 6 },
  { gender: "Male", exercise: "barbell_curl", threshold: 0.45, points: 5 },
  { gender: "Male", exercise: "barbell_curl", threshold: 0.4, points: 4 },
  { gender: "Male", exercise: "barbell_curl", threshold: 0.35, points: 3 },
  { gender: "Male", exercise: "barbell_curl", threshold: 0.3, points: 2 },
  { gender: "Male", exercise: "barbell_curl", threshold: 0.25, points: 1 },
  { gender: "Male", exercise: "pull_down", threshold: 1.2, points: 10 },
  { gender: "Male", exercise: "pull_down", threshold: 1.15, points: 9 },
  { gender: "Male", exercise: "pull_down", threshold: 1.1, points: 8 },
  { gender: "Male", exercise: "pull_down", threshold: 1.05, points: 7 },
  { gender: "Male", exercise: "pull_down", threshold: 1.0, points: 6 },
  { gender: "Male", exercise: "pull_down", threshold: 0.95, points: 5 },
  { gender: "Male", exercise: "pull_down", threshold: 0.9, points: 4 },
  { gender: "Male", exercise: "pull_down", threshold: 0.85, points: 3 },
  { gender: "Male", exercise: "pull_down", threshold: 0.8, points: 2 },
  { gender: "Male", exercise: "pull_down", threshold: 0.75, points: 1 },
  { gender: "Male", exercise: "leg_press", threshold: 3.0, points: 10 },
  { gender: "Male", exercise: "leg_press", threshold: 2.8, points: 9 },
  { gender: "Male", exercise: "leg_press", threshold: 2.6, points: 8 },
  { gender: "Male", exercise: "leg_press", threshold: 2.4, points: 7 },
  { gender: "Male", exercise: "leg_press", threshold: 2.2, points: 6 },
  { gender: "Male", exercise: "leg_press", threshold: 2.0, points: 5 },
  { gender: "Male", exercise: "leg_press", threshold: 1.8, points: 4 },
  { gender: "Male", exercise: "leg_press", threshold: 1.6, points: 3 },
  { gender: "Male", exercise: "leg_press", threshold: 1.4, points: 2 },
  { gender: "Male", exercise: "leg_press", threshold: 1.2, points: 1 },
  { gender: "Male", exercise: "leg_extension", threshold: 0.8, points: 10 },
  { gender: "Male", exercise: "leg_extension", threshold: 0.75, points: 9 },
  { gender: "Male", exercise: "leg_extension", threshold: 0.7, points: 8 },
  { gender: "Male", exercise: "leg_extension", threshold: 0.65, points: 7 },
  { gender: "Male", exercise: "leg_extension", threshold: 0.6, points: 6 },
  { gender: "Male", exercise: "leg_extension", threshold: 0.55, points: 5 },
  { gender: "Male", exercise: "leg_extension", threshold: 0.5, points: 4 },
  { gender: "Male", exercise: "leg_extension", threshold: 0.45, points: 3 },
  { gender: "Male", exercise: "leg_extension", threshold: 0.4, points: 2 },
  { gender: "Male", exercise: "leg_extension", threshold: 0.35, points: 1 },
  { gender: "Male", exercise: "leg_curl", threshold: 0.7, points: 10 },
  { gender: "Male", exercise: "leg_curl", threshold: 0.65, points: 9 },
  { gender: "Male", exercise: "leg_curl", threshold: 0.6, points: 8 },
  { gender: "Male", exercise: "leg_curl", threshold: 0.55, points: 7 },
  { gender: "Male", exercise: "leg_curl", threshold: 0.5, points: 6 },
  { gender: "Male", exercise: "leg_curl", threshold: 0.45, points: 5 },
  { gender: "Male", exercise: "leg_curl", threshold: 0.4, points: 4 },
  { gender: "Male", exercise: "leg_curl", threshold: 0.35, points: 3 },
  { gender: "Male", exercise: "leg_curl", threshold: 0.3, points: 2 },
  { gender: "Male", exercise: "leg_curl", threshold: 0.25, points: 1 },
  { gender: "Female", exercise: "bench_press", threshold: 0.9, points: 10 },
  { gender: "Female", exercise: "bench_press", threshold: 0.85, points: 9 },
  { gender: "Female", exercise: "bench_press", threshold: 0.8, points: 8 },
  { gender: "Female", exercise: "bench_press", threshold: 0.7, points: 7 },
  { gender: "Female", exercise: "bench_press", threshold: 0.65, points: 6 },
  { gender: "Female", exercise: "bench_press", threshold: 0.6, points: 5 },
  { gender: "Female", exercise: "bench_press", threshold: 0.55, points: 4 },
  { gender: "Female", exercise: "bench_press", threshold: 0.5, points: 3 },
  { gender: "Female", exercise: "bench_press", threshold: 0.45, points: 2 },
  { gender: "Female", exercise: "bench_press", threshold: 0.35, points: 1 },
  { gender: "Female", exercise: "barbell_curl", threshold: 0.5, points: 10 },
  { gender: "Female", exercise: "barbell_curl", threshold: 0.45, points: 9 },
  { gender: "Female", exercise: "barbell_curl", threshold: 0.42, points: 8 },
  { gender: "Female", exercise: "barbell_curl", threshold: 0.38, points: 7 },
  { gender: "Female", exercise: "barbell_curl", threshold: 0.35, points: 6 },
  { gender: "Female", exercise: "barbell_curl", threshold: 0.32, points: 5 },
  { gender: "Female", exercise: "barbell_curl", threshold: 0.28, points: 4 },
  { gender: "Female", exercise: "barbell_curl", threshold: 0.25, points: 3 },
  { gender: "Female", exercise: "barbell_curl", threshold: 0.21, points: 2 },
  { gender: "Female", exercise: "barbell_curl", threshold: 0.18, points: 1 },
  { gender: "Female", exercise: "pull_down", threshold: 0.85, points: 10 },
  { gender: "Female", exercise: "pull_down", threshold: 0.8, points: 9 },
  { gender: "Female", exercise: "pull_down", threshold: 0.75, points: 8 },
  { gender: "Female", exercise: "pull_down", threshold: 0.73, points: 7 },
  { gender: "Female", exercise: "pull_down", threshold: 0.7, points: 6 },
  { gender: "Female", exercise: "pull_down", threshold: 0.65, points: 5 },
  { gender: "Female", exercise: "pull_down", threshold: 0.63, points: 4 },
  { gender: "Female", exercise: "pull_down", threshold: 0.6, points: 3 },
  { gender: "Female", exercise: "pull_down", threshold: 0.55, points: 2 },
  { gender: "Female", exercise: "pull_down", threshold: 0.5, points: 1 },
  { gender: "Female", exercise: "leg_press", threshold: 2.7, points: 10 },
  { gender: "Female", exercise: "leg_press", threshold: 2.5, points: 9 },
  { gender: "Female", exercise: "leg_press", threshold: 2.3, points: 8 },
  { gender: "Female", exercise: "leg_press", threshold: 2.1, points: 7 },
  { gender: "Female", exercise: "leg_press", threshold: 2.0, points: 6 },
  { gender: "Female", exercise: "leg_press", threshold: 1.8, points: 5 },
  { gender: "Female", exercise: "leg_press", threshold: 1.6, points: 4 },
  { gender: "Female", exercise: "leg_press", threshold: 1.4, points: 3 },
  { gender: "Female", exercise: "leg_press", threshold: 1.2, points: 2 },
  { gender: "Female", exercise: "leg_press", threshold: 1.0, points: 1 },
  { gender: "Female", exercise: "leg_extension", threshold: 0.7, points: 10 },
  { gender: "Female", exercise: "leg_extension", threshold: 0.65, points: 9 },
  { gender: "Female", exercise: "leg_extension", threshold: 0.6, points: 8 },
  { gender: "Female", exercise: "leg_extension", threshold: 0.55, points: 7 },
  { gender: "Female", exercise: "leg_extension", threshold: 0.52, points: 6 },
  { gender: "Female", exercise: "leg_extension", threshold: 0.5, points: 5 },
  { gender: "Female", exercise: "leg_extension", threshold: 0.45, points: 4 },
  { gender: "Female", exercise: "leg_extension", threshold: 0.4, points: 3 },
  { gender: "Female", exercise: "leg_extension", threshold: 0.35, points: 2 },
  { gender: "Female", exercise: "leg_extension", threshold: 0.3, points: 1 },
  { gender: "Female", exercise: "leg_curl", threshold: 0.6, points: 10 },
  { gender: "Female", exercise: "leg_curl", threshold: 0.55, points: 9 },
  { gender: "Female", exercise: "leg_curl", threshold: 0.52, points: 8 },
  { gender: "Female", exercise: "leg_curl", threshold: 0.5, points: 7 },
  { gender: "Female", exercise: "leg_curl", threshold: 0.45, points: 6 },
  { gender: "Female", exercise: "leg_curl", threshold: 0.4, points: 5 },
  { gender: "Female", exercise: "leg_curl", threshold: 0.35, points: 4 },
  { gender: "Female", exercise: "leg_curl", threshold: 0.3, points: 3 },
  { gender: "Female", exercise: "leg_curl", threshold: 0.25, points: 2 },
  { gender: "Female", exercise: "leg_curl", threshold: 0.2, points: 1 },
];

export const sitUpConfig = [
  { gender: "Male", age: 15, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 15, threshold: 33, classification: "Abaixo da média" },
  { gender: "Male", age: 15, threshold: 38, classification: "Média" },
  { gender: "Male", age: 15, threshold: 42, classification: "Acima da média" },
  { gender: "Male", age: 15, threshold: 48, classification: "Excelente" },
  { gender: "Female", age: 15, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 15,
    threshold: 27,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 15, threshold: 32, classification: "Média" },
  {
    gender: "Female",
    age: 15,
    threshold: 36,
    classification: "Acima da média",
  },
  { gender: "Female", age: 15, threshold: 42, classification: "Excelente" },
  { gender: "Male", age: 20, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 20, threshold: 29, classification: "Abaixo da média" },
  { gender: "Male", age: 20, threshold: 33, classification: "Média" },
  { gender: "Male", age: 20, threshold: 37, classification: "Acima da média" },
  { gender: "Male", age: 20, threshold: 43, classification: "Excelente" },
  { gender: "Female", age: 20, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 20,
    threshold: 21,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 20, threshold: 25, classification: "Média" },
  {
    gender: "Female",
    age: 20,
    threshold: 31,
    classification: "Acima da média",
  },
  { gender: "Female", age: 20, threshold: 36, classification: "Excelente" },
  { gender: "Male", age: 30, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 30, threshold: 22, classification: "Abaixo da média" },
  { gender: "Male", age: 30, threshold: 27, classification: "Média" },
  { gender: "Male", age: 30, threshold: 31, classification: "Acima da média" },
  { gender: "Male", age: 30, threshold: 36, classification: "Excelente" },
  { gender: "Female", age: 30, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 30,
    threshold: 15,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 30, threshold: 20, classification: "Média" },
  {
    gender: "Female",
    age: 30,
    threshold: 24,
    classification: "Acima da média",
  },
  { gender: "Female", age: 30, threshold: 29, classification: "Excelente" },
  { gender: "Male", age: 40, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 40, threshold: 17, classification: "Abaixo da média" },
  { gender: "Male", age: 40, threshold: 22, classification: "Média" },
  { gender: "Male", age: 40, threshold: 26, classification: "Acima da média" },
  { gender: "Male", age: 40, threshold: 31, classification: "Excelente" },
  { gender: "Female", age: 40, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 40,
    threshold: 7,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 40, threshold: 15, classification: "Média" },
  {
    gender: "Female",
    age: 40,
    threshold: 20,
    classification: "Acima da média",
  },
  { gender: "Female", age: 40, threshold: 25, classification: "Excelente" },
  { gender: "Male", age: 50, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 50, threshold: 13, classification: "Abaixo da média" },
  { gender: "Male", age: 50, threshold: 18, classification: "Média" },
  { gender: "Male", age: 50, threshold: 22, classification: "Acima da média" },
  { gender: "Male", age: 50, threshold: 26, classification: "Excelente" },
  { gender: "Female", age: 50, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 50,
    threshold: 3,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 50, threshold: 5, classification: "Média" },
  {
    gender: "Female",
    age: 50,
    threshold: 12,
    classification: "Acima da média",
  },
  { gender: "Female", age: 50, threshold: 19, classification: "Excelente" },
  { gender: "Male", age: 60, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 60, threshold: 7, classification: "Abaixo da média" },
  { gender: "Male", age: 60, threshold: 12, classification: "Média" },
  { gender: "Male", age: 60, threshold: 17, classification: "Acima da média" },
  { gender: "Male", age: 60, threshold: 23, classification: "Excelente" },
  { gender: "Female", age: 60, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 60,
    threshold: 2,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 60, threshold: 4, classification: "Média" },
  {
    gender: "Female",
    age: 60,
    threshold: 12,
    classification: "Acima da média",
  },
  { gender: "Female", age: 60, threshold: 16, classification: "Excelente" },
];

export const pushUpConfig = [
  { gender: "Male", age: 15, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 15, threshold: 18, classification: "Abaixo da média" },
  { gender: "Male", age: 15, threshold: 23, classification: "Média" },
  { gender: "Male", age: 15, threshold: 29, classification: "Acima da média" },
  { gender: "Male", age: 15, threshold: 39, classification: "Excelente" },
  { gender: "Female", age: 15, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 15,
    threshold: 12,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 15, threshold: 18, classification: "Média" },
  {
    gender: "Female",
    age: 15,
    threshold: 25,
    classification: "Acima da média",
  },
  { gender: "Female", age: 15, threshold: 33, classification: "Excelente" },
  { gender: "Male", age: 20, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 20, threshold: 17, classification: "Abaixo da média" },
  { gender: "Male", age: 20, threshold: 22, classification: "Média" },
  { gender: "Male", age: 20, threshold: 29, classification: "Acima da média" },
  { gender: "Male", age: 20, threshold: 36, classification: "Excelente" },
  { gender: "Female", age: 20, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 20,
    threshold: 10,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 20, threshold: 15, classification: "Média" },
  {
    gender: "Female",
    age: 20,
    threshold: 21,
    classification: "Acima da média",
  },
  { gender: "Female", age: 20, threshold: 30, classification: "Excelente" },
  { gender: "Male", age: 30, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 30, threshold: 12, classification: "Abaixo da média" },
  { gender: "Male", age: 30, threshold: 17, classification: "Média" },
  { gender: "Male", age: 30, threshold: 22, classification: "Acima da média" },
  { gender: "Male", age: 30, threshold: 30, classification: "Excelente" },
  { gender: "Female", age: 30, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 30,
    threshold: 8,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 30, threshold: 13, classification: "Média" },
  {
    gender: "Female",
    age: 30,
    threshold: 20,
    classification: "Acima da média",
  },
  { gender: "Female", age: 30, threshold: 27, classification: "Excelente" },
  { gender: "Male", age: 40, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 40, threshold: 10, classification: "Abaixo da média" },
  { gender: "Male", age: 40, threshold: 13, classification: "Média" },
  { gender: "Male", age: 40, threshold: 17, classification: "Acima da média" },
  { gender: "Male", age: 40, threshold: 22, classification: "Excelente" },
  { gender: "Female", age: 40, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 40,
    threshold: 5,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 40, threshold: 11, classification: "Média" },
  {
    gender: "Female",
    age: 40,
    threshold: 15,
    classification: "Acima da média",
  },
  { gender: "Female", age: 40, threshold: 24, classification: "Excelente" },
  { gender: "Male", age: 50, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 50, threshold: 7, classification: "Abaixo da média" },
  { gender: "Male", age: 50, threshold: 10, classification: "Média" },
  { gender: "Male", age: 50, threshold: 13, classification: "Acima da média" },
  { gender: "Male", age: 50, threshold: 21, classification: "Excelente" },
  { gender: "Female", age: 50, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 50,
    threshold: 2,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 50, threshold: 7, classification: "Média" },
  {
    gender: "Female",
    age: 50,
    threshold: 11,
    classification: "Acima da média",
  },
  { gender: "Female", age: 50, threshold: 21, classification: "Excelente" },
  { gender: "Male", age: 60, threshold: 0, classification: "Ruim" },
  { gender: "Male", age: 60, threshold: 5, classification: "Abaixo da média" },
  { gender: "Male", age: 60, threshold: 8, classification: "Média" },
  { gender: "Male", age: 60, threshold: 11, classification: "Acima da média" },
  { gender: "Male", age: 60, threshold: 18, classification: "Excelente" },
  { gender: "Female", age: 60, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 60,
    threshold: 2,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 60, threshold: 5, classification: "Média" },
  {
    gender: "Female",
    age: 60,
    threshold: 12,
    classification: "Acima da média",
  },
  { gender: "Female", age: 60, threshold: 17, classification: "Excelente" },
];

export const jumpConfig = [
  { gender: "Male", age: 11, threshold: 0, classification: "Ruim" },
  {
    gender: "Male",
    age: 11,
    threshold: 180,
    classification: "Abaixo da média",
  },
  { gender: "Male", age: 11, threshold: 190, classification: "Média" },
  { gender: "Male", age: 11, threshold: 200, classification: "Acima da média" },
  { gender: "Male", age: 11, threshold: 210, classification: "Excelente" },
  { gender: "Female", age: 11, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 11,
    threshold: 178,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 11, threshold: 186, classification: "Média" },
  {
    gender: "Female",
    age: 11,
    threshold: 194,
    classification: "Acima da média",
  },
  { gender: "Female", age: 11, threshold: 202, classification: "Excelente" },
  { gender: "Male", age: 13, threshold: 0, classification: "Ruim" },
  {
    gender: "Male",
    age: 13,
    threshold: 207,
    classification: "Abaixo da média",
  },
  { gender: "Male", age: 13, threshold: 221, classification: "Média" },
  { gender: "Male", age: 13, threshold: 232, classification: "Acima da média" },
  { gender: "Male", age: 13, threshold: 246, classification: "Excelente" },
  { gender: "Female", age: 13, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 13,
    threshold: 183,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 13, threshold: 188, classification: "Média" },
  {
    gender: "Female",
    age: 13,
    threshold: 196,
    classification: "Acima da média",
  },
  { gender: "Female", age: 13, threshold: 208, classification: "Excelente" },
  { gender: "Male", age: 15, threshold: 0, classification: "Ruim" },
  {
    gender: "Male",
    age: 15,
    threshold: 229,
    classification: "Abaixo da média",
  },
  { gender: "Male", age: 15, threshold: 243, classification: "Média" },
  { gender: "Male", age: 15, threshold: 257, classification: "Acima da média" },
  { gender: "Male", age: 15, threshold: 271, classification: "Excelente" },
  { gender: "Female", age: 15, threshold: 0, classification: "Ruim" },
  {
    gender: "Female",
    age: 15,
    threshold: 192,
    classification: "Abaixo da média",
  },
  { gender: "Female", age: 15, threshold: 199, classification: "Média" },
  {
    gender: "Female",
    age: 15,
    threshold: 206,
    classification: "Acima da média",
  },
  { gender: "Female", age: 15, threshold: 223, classification: "Excelente" },
];
