export const schema = {
  abdominal_circumference: "required|between:0,999",
  waist_circumference: "required|between:0,999",
  hip_circumference: "required|between:0,999",
  thighs_circumference: "between:0,999",
  right_biceps_circumference: "between:0,999",
  right_forearm_circumference: "between:0,999",
  chest_skinfold: "between:0,999",
  abdominal_skinfold: "between:0,999",
  thighs_skinfold: "between:0,999",
  triceps_skinfold: "between:0,999",
  suprailiac_skinfold: "between:0,999",
  subscapularis_skinfold: "between:0,999",
  midaxillary_skinfold: "between:0,999",
  iliac_circumference: "between:0,999",
};
