export const schema = {
  abdominal_circumference: "required|between:0,999",
  waist_circumference: "required|between:0,999",
  hip_circumference: "required|between:0,999",
  thighs_circumference: "between:0,999",
  right_biceps_circumference: "between:0,999",
  right_forearm_circumference: "between:0,999",
  chest_skin_fold: "between:0,999",
  abdominal_skin_fold: "between:0,999",
  thighs_skin_fold: "between:0,999",
  triceps_skin_fold: "between:0,999",
  suprailiac_skin_fold: "between:0,999",
  subscapularis_skin_fold: "between:0,999",
  midaxillary_skin_fold: "between:0,999",
  iliac_circumference: "between:0,999",
};
