version: "3.2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conforfit-db-app
    ports:
      - 3333:80

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
